
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app


COPY ["api/BancoDeGatos.API/BancoDeGatos.API.csproj", "api/BancoDeGatos.API/"]
COPY ["api/BancoDeGatos.Dados/BancoDeGatos.Dados.csproj", "api/BancoDeGatos.Dados/"]
COPY ["api/BancoDeGatos.sln", "api/"]

RUN dotnet restore "api/BancoDeGatos.sln"


COPY api/. ./api/


RUN dotnet publish "api/BancoDeGatos.API/BancoDeGatos.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BancoDeGatos.API.dll"]