version: '3.8'

services:
  banco_de_gatos:
    image: mysql:8.0
    container_name: banco_de_gatos_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: BancoDeGatos
    volumes:
      - ./db/gatos.sql:/docker-entrypoint-initdb.d/gatos.sql
      - banco_dados_volume:/var/lib/mysql
    networks:
      - rede_aplicacao

  api_gatos:
   build:
     context: .
     dockerfile: Dockerfile-api
   container_name: api_gatos_container
   ports:
     - "8080:8080"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development 
   depends_on:
     - banco_de_gatos
   networks: 
     - rede_aplicacao
   restart: always
   deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: 256M

networks:
  rede_aplicacao:
    driver: bridge

volumes:
  banco_dados_volume: